controllers/NewsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\News;
use app\models\search\SearchNews;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['view'],
                        'allow' => true,
                        'roles' => ['user'],
                    ],
                    [
                        'actions' => ['create', 'update'],
                        'allow' => true,
                        'roles' => ['moderator'],
                    ],
                    [
                        'actions' => ['delete'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Displays a single News model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionCreate($id = null)
    {
        $model = (null == $id) ? new News() : $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['site/index']);
        } else {
            return $this->render('form', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing News model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        return $this->actionCreate($id);
    }

    /**
     * Deletes an existing News model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['site/index']);
    }

    /**
     * Finds the News model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return News the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = News::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\forms\SetPasswordForm;
use app\models\forms\SignupForm;
use app\models\search\SearchNews;
use app\models\Users;
use Yii;
use yii\filters\AccessControl;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\forms\LoginForm;
use yii\web\NotFoundHttpException;

/**
 * SiteController servicing main site operations
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['user'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['guest'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Lists all News preview.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new SearchNews();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Login page
     *
     * @return string|\yii\web\Response
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Registration Page
     *
     * @return string|\yii\web\Response
     */
    public function actionSignUp()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post()) && $model->signup()) {
            return $this->goBack();
        }
        return $this->render('sign-up', [
            'model' => $model,
        ]);
    }

    /**
     * Automatic email activation for registered user and password setting page for user registered by admin
     *
     * @param $token
     *
     * @return string|\yii\web\Response
     * @throws BadRequestHttpException
     * @throws NotFoundHttpException
     */
    public function actionActivation($token)
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $user = Users::findIdentityByAccessToken($token);
        /* @var $user Users */
        if($user) {
            $user->is_email_activated = Users::EMAIL_ACTIVATED;
            if(empty($user->password_hash)) {
                $model = new SetPasswordForm();
                if (!$model->load(Yii::$app->request->post()) || (null == $model->setPassword($user))) {
                    return $this->render('set-password', [
                        'model' => $model,
                    ]);
                }
            }
            $user->email_activation_token = '';
            if($user->save(false, ['is_email_activated', 'email_activation_token'])) {
                Yii::$app->user->login($user);
                return $this->goHome();
            } else {
                throw new BadRequestHttpException();
            }
        }
        throw new NotFoundHttpException();
    }

    /**
     * Logout
     *
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

}

views/site/_news_item.php
<?php
/* @var $model \app\models\News */
?>
<div class="news_item">
    <div class="news_title"><?=$model->title;?></div>
    <div class="news_short_description"><?=$model->short_description;?></div>
    <?php if (Yii::$app->user->can('viewDetailNews')) { ?>
        <div class="news_link"><?=\yii\helpers\Html::a('details...', $model->url);?></div>
    <?php } ?>
</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?=Html::encode($this->title)?></h1>

    <div class="alert alert-danger">
        <?=nl2br(Html::encode($message))?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>

    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\SearchNews */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'News';
?>
<div class="news-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php if(Yii::$app->user->can('createNews')) { ?>
            <?= Html::a('Create News', ['news/create'], ['class' => 'btn btn-success']) ?>
        <?php }?>
    </p>
    <? \yii\widgets\Pjax::begin(['id' => 'main_page_news'])?>
        <?= Html::dropDownList('perPage', $searchModel->perPage, $searchModel->getPerPageValues(), [
            'onchange' => '$.pjax.reload("#main_page_news", {
                url : \'/\' + \'?per-page=\' + $(this).val()
            });',
        ]);?>
        <?= \yii\widgets\ListView::widget([
            'dataProvider' => $dataProvider,
            'itemView' => '_news_item',
        ]); ?>
    <? \yii\widgets\Pjax::end();?>
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?=Html::encode($this->title)?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id'          => 'login-form',
        'options'     => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template'     => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?=$form->field($model, 'email')->textInput(['autofocus' => true])?>

    <?=$form->field($model, 'password')->passwordInput()?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?=Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button'])?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin@admin.ru/123456</strong>.<br>
    </div>
    <div class="col-lg-offset-1" style="color:#999;">
        <a href="<?=\yii\helpers\Url::toRoute('site/sign-up');?>">Registration</a><br>
    </div>
</div>

views/site/set-password.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\forms\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Set password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?=Html::encode($this->title)?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id'          => 'set-password-form',
        'options'     => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template'     => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?=$form->field($model, 'password')->passwordInput()?>

    <?=$form->field($model, 'password_confirm')->passwordInput()?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?=Html::submitButton('Send', ['class' => 'btn btn-primary', 'name' => 'set-password-button'])?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/site/sign-up.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\forms\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Registration';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?=Html::encode($this->title)?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id'          => 'registration-form',
        'options'     => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template'     => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

    <?=$form->field($model, 'email')->textInput(['autofocus' => true])?>

    <?=$form->field($model, 'password')->passwordInput()?>

    <?=$form->field($model, 'password_confirm')->passwordInput()?>

    <div class="form-group">
        <div class="col-lg-offset-1 col-lg-11">
            <?=Html::submitButton('Send', ['class' => 'btn btn-primary', 'name' => 'registration-button'])?>
        </div>
    </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        <a href="<?=\yii\helpers\Url::toRoute('site/login');?>">Login</a><br>
    </div>
</div>