models/News.php
<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\helpers\Url;

/**
 * This is the model class for table "news".
 *
 * @property integer $id
 * @property string $title
 * @property string $short_description
 * @property string $full_text
 * @property integer $author_id
 * @property string $created_at
 * @property string $updated_at
 *
 * @property string $url
 * @property Users $author
 */
class News extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'news';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            [
                'class'              => TimestampBehavior::className(),
                'createdAtAttribute' => 'created_at',
                'updatedAtAttribute' => 'updated_at',
                'value'              => new Expression('NOW()'),
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'short_description', 'full_text'], 'required'],
            [['short_description', 'full_text'], 'string'],
            [['author_id'], 'integer'],
            [['author_id'], 'default', 'value' => Yii::$app->user ? Yii::$app->user->id : 0],
            [['created_at', 'updated_at'], 'safe'],
            [['title'], 'string', 'max' => 120],
            [
                ['author_id'],
                'exist',
                'skipOnError'     => true,
                'targetClass'     => Users::className(),
                'targetAttribute' => ['author_id' => 'id']
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'                => 'ID',
            'title'             => 'Title',
            'short_description' => 'Short Description',
            'full_text'         => 'Full Text',
            'author_id'         => 'Author ID',
            'created_at'        => 'Created At',
            'updated_at'        => 'Updated At',
        ];
    }

    /**
     * Url to news item page
     *
     * @return string
     */
    public function getUrl()
    {
        return Url::toRoute(['news/view', 'id' => $this->id], true);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Users::className(), ['id' => 'author_id']);
    }
}

controllers/NewsController.php
<?php

namespace app\controllers;

use Yii;
use app\models\News;
use app\models\search\SearchNews;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * NewsController implements the CRUD actions for News model.
 */
class NewsController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['view'],
                        'allow' => true,
                        'roles' => ['user'],
                    ],
                    [
                        'actions' => ['create', 'update'],
                        'allow' => true,
                        'roles' => ['moderator'],
                    ],
                    [
                        'actions' => ['delete'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Displays a single News model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new News model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     *
     * @param integer $id
     * @return mixed
     */
    public function actionCreate($id = null)
    {
        $model = (null == $id) ? new News() : $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['site/index']);
        } else {
            return $this->render('form', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing News model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        return $this->actionCreate($id);
    }

    /**
     * Deletes an existing News model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['site/index']);
    }

    /**
     * Finds the News model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return News the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = News::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/news/form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\News */
/* @var $form yii\widgets\ActiveForm */

$this->title = (($model->isNewRecord) ? 'Create' : 'Update').' news';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="news-form">
    <h1><?=Html::encode($this->title)?></h1>

    <div class="users-form">

        <?php $form = ActiveForm::begin(); ?>

        <?=$form->field($model, 'title')->textInput(['maxlength' => true])?>

        <?=$form->field($model, 'short_description')->textarea(['rows' => 6])?>

        <?=$form->field($model, 'full_text')->textarea(['rows' => 6])?>

        <div class="form-group">
            <?=Html::submitButton($model->isNewRecord ? 'Create' : 'Update',
                ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary'])?>
        </div>

        <?php ActiveForm::end(); ?>

    </div>
</div>

views/news/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\News */

$this->title = $model->title;
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="news-view">

    <h1><?=Html::encode($this->title)?></h1>

    <p>
        <?php if (Yii::$app->user->can('updateNews')) { ?>
            <?=Html::a('Update', ['news/update', 'id' => $model->id], ['class' => 'btn btn-primary'])?>
        <?php } ?>
        <?php if (Yii::$app->user->can('deleteNews')) { ?>
            <?=Html::a('Delete', ['news/delete', 'id' => $model->id], [
                'class' => 'btn btn-danger',
                'data'  => [
                    'confirm' => 'Are you sure you want to delete this item?',
                    'method'  => 'post',
                ],
            ])?>
        <?php } ?>
    </p>

    <?=DetailView::widget([
        'model'      => $model,
        'attributes' => [
            'id',
            'title',
            'short_description:ntext',
            'full_text:ntext',
            'author_id',
            'created_at',
            'updated_at',
        ],
    ])?>

</div>